### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SubMGRru** [valumar/dialogflow-bot#1]
help pls
`root@vultr:~/bot/dialogflow-bot-master# python3 bot-vk.py
Traceback (most recent call last):
  File "bot-vk.py", line 35, in <module>
    echo(event, vk_api)
  File "bot-vk.py", line 17, in echo
    message = query_dflow(event.user_id, event.text)
  File "/root/bot/dialogflow-bot-master/dflow_tools.py", line 31, in query_dflow
    if data["result"]["metadata"]["isFallbackIntent"] == "true":
KeyError: 'isFallbackIntent'`

**Comment by valumar** [comment]
See README.md

> Please note this app works only with DialogFlow V1 API (Will be shut down on October 23rd, 2019)
